"""make user_id nullable, add session_id to predictions

Revision ID: c79701f997ca
Revises: 995db7203289
Create Date: 2026-07-28 18:49:22.956477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79701f997ca'
down_revision: Union[str, Sequence[str], None] = '995db7203289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('session_id', sa.String(), nullable=True))
    op.alter_column('predictions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_predictions_session_id'), 'predictions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_session_id'), table_name='predictions')
    op.alter_column('predictions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('predictions', 'session_id')
    # ### end Alembic commands ###
